# Generated by Django 5.2.5 on 2025-08-27 16:28

import django.core.validators
import django.db.models.deletion
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Имя')),
                ('phonenumber', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='RU', verbose_name='Телефон')),
                ('mail', models.CharField(max_length=256, verbose_name='Почта')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('levels_amount', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)], verbose_name='Количество уровней')),
                ('form', models.CharField(choices=[('CIRCLE', 'Круг'), ('SQUARE', 'Квадрат'), ('RECTANGLE', 'Прямоугольник')], default='Круг', max_length=256, verbose_name='Форма')),
                ('topping', models.CharField(choices=[('NONE', 'Без'), ('WHITE', 'Белый соус'), ('CARAMEL', 'Карамельный'), ('MAPLE', 'Кленовый'), ('BLUEBERRIES', 'Черника'), ('MILK_CHOCOLATE', 'Молочный шоколад'), ('STRAWBERRY', 'Клубника')], default='Без', max_length=256, verbose_name='Топпинг')),
                ('berries', models.CharField(choices=[('NONE', 'Без'), ('BLACKBERRY', 'Ежевика'), ('RASPBERRY', 'Малина'), ('BLUEBERRY', 'Голубика'), ('STRAWBERRY', 'Клубника')], default='Без', max_length=256, verbose_name='Ягоды')),
                ('decor', models.CharField(choices=[('NONE', 'Без'), ('PISTACHIOUS', 'Фисташки'), ('MERINGUE', 'Безе'), ('HAZELNUT', 'Фундук'), ('PECANS', 'Пекан'), ('MARSHMALLOWS', 'Маршмэллоу'), ('MARZEPAN', 'Марцепан')], default='Без', verbose_name='Декор')),
                ('sign', models.CharField(max_length=256, verbose_name='Надпись')),
                ('comment', models.TextField(max_length=500, verbose_name='Комментарий')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='cakes_app.client', verbose_name='Клиент')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
    ]
