# Generated by Django 5.2.5 on 2025-08-27 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cakes_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CakePictures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('picture', models.ImageField(upload_to='place_pictures/')),
            ],
        ),
    ]
