# Generated by Django 5.2.5 on 2025-08-30 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cakes_app', '0002_promocode'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='promo_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
