# Generated by Django 5.2.5 on 2025-08-31 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cakes_app', '0003_order_promo_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.CharField(blank=True, max_length=256, verbose_name='Адрес доставки'),
        ),
    ]
