# Generated by Django 5.2.5 on 2025-08-28 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cakes_app', '0003_berry_decor_form_level_topping_delete_cakepictures_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='berries',
        ),
        migrations.RemoveField(
            model_name='order',
            name='decor',
        ),
        migrations.AddField(
            model_name='order',
            name='berries',
            field=models.ManyToManyField(null=True, related_name='orders', to='cakes_app.berry', verbose_name='Ягоды'),
        ),
        migrations.AddField(
            model_name='order',
            name='decor',
            field=models.ManyToManyField(null=True, related_name='orders', to='cakes_app.decor', verbose_name='Декор'),
        ),
    ]
