# Generated by Django 5.2.5 on 2025-08-28 10:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cakes_app', '0004_remove_order_berries_remove_order_decor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Итоговая стоимость'),
        ),
        migrations.AlterField(
            model_name='order',
            name='berries',
            field=models.ManyToManyField(blank=True, related_name='orders', to='cakes_app.berry', verbose_name='Ягоды'),
        ),
        migrations.AlterField(
            model_name='order',
            name='decor',
            field=models.ManyToManyField(blank=True, related_name='orders', to='cakes_app.decor', verbose_name='Декор'),
        ),
    ]
