# Generated by Django 5.2.5 on 2025-08-31 16:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cakes_app', '0005_order_date_order_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='order',
            name='time',
            field=models.TimeField(default=django.utils.timezone.now, verbose_name='Время'),
        ),
    ]
