# Generated by Django 5.2.5 on 2025-08-31 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cakes_app', '0006_alter_order_date_alter_order_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='deliv_comment',
            field=models.TextField(blank=True, max_length=500, verbose_name='Комментарий к доставке'),
        ),
    ]
