# Generated by Django 5.2.5 on 2025-08-31 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cakes_app', '0007_order_deliv_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='promocode',
            options={'verbose_name': 'Промокод', 'verbose_name_plural': 'Промокоды'},
        ),
    ]
